2022-01-20 20:23:16,549 INFO    Thread-32 :224864 [wandb_setup.py:_flush():71] setting env: {'entity': 'amazonproject', 'project': 'Amazon-Reviews-v2', 'root_dir': '/zhome/4a/f/117237/Documents/MLOps_Amazon_review_project', 'run_id': '6axeewi8', 'sweep_param_path': '/zhome/4a/f/117237/Documents/MLOps_Amazon_review_project/wandb/sweep-igrmn63w/config-6axeewi8.yaml', 'sweep_id': 'igrmn63w'}
2022-01-20 20:23:16,550 INFO    Thread-32 :224864 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-20 20:23:16,550 INFO    Thread-32 :224864 [wandb_init.py:_log_setup():371] Logging user logs to /zhome/4a/f/117237/Documents/MLOps_Amazon_review_project/wandb/run-20220120_202316-6axeewi8/logs/debug.log
2022-01-20 20:23:16,550 INFO    Thread-32 :224864 [wandb_init.py:_log_setup():372] Logging internal logs to /zhome/4a/f/117237/Documents/MLOps_Amazon_review_project/wandb/run-20220120_202316-6axeewi8/logs/debug-internal.log
2022-01-20 20:23:16,551 INFO    Thread-32 :224864 [wandb_init.py:init():404] calling init triggers
2022-01-20 20:23:16,551 INFO    Thread-32 :224864 [wandb_init.py:init():411] wandb.init called with sweep_config: {'batch_size': 200, 'drop_out': 0.15, 'lr': 0.001, 'optimizer': 'sgd'}
config: {}
2022-01-20 20:23:16,551 INFO    Thread-32 :224864 [wandb_init.py:init():460] starting backend
2022-01-20 20:23:16,551 INFO    Thread-32 :224864 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-20 20:23:16,561 INFO    Thread-32 :224864 [backend.py:ensure_launched():216] starting backend process...
2022-01-20 20:23:16,574 INFO    Thread-32 :224864 [backend.py:ensure_launched():222] started backend process with pid: 230051
2022-01-20 20:23:16,588 INFO    Thread-32 :224864 [wandb_init.py:init():469] backend started and connected
2022-01-20 20:23:16,590 INFO    Thread-32 :224864 [wandb_run.py:_config_callback():956] config_cb None None {'batch_size': 200, 'drop_out': 0.15, 'lr': 0.001, 'optimizer': 'sgd'}
2022-01-20 20:23:16,591 INFO    Thread-32 :224864 [wandb_init.py:init():533] updated telemetry
2022-01-20 20:23:16,639 INFO    Thread-32 :224864 [wandb_init.py:init():563] communicating current version
2022-01-20 20:23:17,718 INFO    Thread-32 :224864 [wandb_init.py:init():568] got version response 
2022-01-20 20:23:17,718 INFO    Thread-32 :224864 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-20 20:23:17,950 INFO    Thread-32 :224864 [wandb_init.py:init():606] starting run threads in backend
2022-01-20 20:23:18,026 INFO    Thread-32 :224864 [wandb_run.py:_console_start():1810] atexit reg
2022-01-20 20:23:18,028 INFO    Thread-32 :224864 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-20 20:23:18,028 INFO    Thread-32 :224864 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-20 20:23:18,028 ERROR   Thread-32 :224864 [wandb_run.py:_redirect():1748] Failed to redirect.
Traceback (most recent call last):
  File "/zhome/4a/f/117237/.local/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1741, in _redirect
    out_redir.install()
  File "/zhome/4a/f/117237/.local/lib/python3.6/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/zhome/4a/f/117237/.local/lib/python3.6/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/zhome/4a/f/117237/.local/lib/python3.6/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib64/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-01-20 20:23:18,029 INFO    Thread-32 :224864 [wandb_init.py:init():633] run started, returning control to user process
2022-01-20 20:29:14,398 ERROR   Thread-1  :224864 [internal_api.py:execute():144] 502 response executing GraphQL.
2022-01-20 20:29:14,400 ERROR   Thread-1  :224864 [internal_api.py:execute():145] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2022-01-20 20:36:52,625 INFO    Thread-32 :224864 [wandb_run.py:finish():1457] finishing run amazonproject/Amazon-Reviews-v2/6axeewi8
2022-01-20 20:36:52,625 INFO    Thread-32 :224864 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-20 20:36:52,627 INFO    Thread-32 :224864 [wandb_run.py:_restore():1752] restore
2022-01-20 20:36:52,635 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 788
}

2022-01-20 20:36:52,920 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 788
}

2022-01-20 20:36:53,413 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 788
}

2022-01-20 20:36:53,515 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 2406
}

2022-01-20 20:36:53,617 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 2406
}

2022-01-20 20:36:53,719 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}

2022-01-20 20:36:53,821 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}

2022-01-20 20:36:53,922 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}

2022-01-20 20:36:54,024 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}

2022-01-20 20:36:54,125 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}

2022-01-20 20:36:54,227 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}

2022-01-20 20:36:54,722 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}

2022-01-20 20:36:55,208 INFO    Thread-32 :224864 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2406
  total_bytes: 2406
}
local_info {
}

2022-01-20 20:36:56,315 INFO    Thread-32 :224864 [wandb_run.py:_append_history():2130] rendering history
2022-01-20 20:36:56,315 INFO    Thread-32 :224864 [wandb_run.py:_append_summary():2085] rendering summary
2022-01-20 20:36:56,315 INFO    Thread-32 :224864 [wandb_run.py:_append_files():2180] logging synced files
